# MikroWARP native installer. Generated by standard/routeros/build.py.
# RouterOS 7.23+, x86-64 CHR. Container package/device mode are prerequisites.
# Re-import to resume. No scheduler or installed System script is created.
:global mikrowarpAction
:global mikrowarpOptions
:local action $mikrowarpAction
:local options $mikrowarpOptions
:set mikrowarpAction
:set mikrowarpOptions
:if ([:typeof $action] = "nothing") do={ :set action "apply" }
:if ([:typeof $options] = "nothing") do={ :set options [:toarray ""] }
:if (($action != "apply") && ($action != "status") && ($action != "rollback") && ($action != "abort")) do={ :error "MikroWARP: action must be status, rollback, abort, or unset" }
:if ([:typeof $options] != "array") do={ :error "MikroWARP: mikrowarpOptions must be an array" }
:local version [/system/resource/get version]
:local major [:tonum [:pick $version 0 [:find $version "."]]]
:local rest [:pick $version ([:find $version "."] + 1) [:len $version]]
:local digits ""
:for i from=0 to=([:len $rest] - 1) do={
    :local c [:pick $rest $i ($i + 1)]
    :if (([:len $digits] = $i) && ($c ~ "^[0-9]\$")) do={ :set digits ($digits . $c) }
}
:local minor [:tonum $digits]
:if (($major != 7) || ([:typeof $minor] != "num") || ($minor < 23)) do={ :error "MikroWARP requires RouterOS 7.23 or newer in the v7 series" }
:if ([/system/resource/get architecture-name] != "x86_64") do={ :error "MikroWARP Standard currently supports x86-64 CHR only" }

:local alive do={
    :local yes false
    :do { :if ([:tostr [/system/script/job/get $job started]] = $started) do={ :set yes true } } on-error={}
    :return $yes
}
:local lockPath "mikrowarp-operation.lock.json"
:local oldLock [/file/find where name=$lockPath]
:if ([:len $oldLock] > 0) do={
    :local lock [:deserialize from=json value=[/file/get $oldLock contents] options=json.no-string-conversion]
    :if (($lock->"format") != "mikrowarp-lock-v1") do={ :error "MikroWARP: lock filename is occupied by an unrelated file" }
    :if ([$alive job=($lock->"job") started=($lock->"started")]) do={ :error "MikroWARP: another operation is running; let it finish before importing again" }
    :if ((($lock->"job") = "") && (([:timestamp] - [:totime ($lock->"created")]) < 10s)) do={ :error "MikroWARP: another import is starting; retry in ten seconds" }
    # Recheck a stale claim immediately before removing it; another importer
    # may already have reclaimed the same filename while this one was parsing.
    :local latest [:deserialize from=json value=[/file/get $oldLock contents] options=json.no-string-conversion]
    :if ((($latest->"token") != ($lock->"token")) || [$alive job=($latest->"job") started=($latest->"started")]) do={ :error "MikroWARP: another import claimed the operation; retry after it finishes" }
    :local oldLog ($lock->"log")
    :if ($oldLog ~ "^mikrowarp-operation-[0-9a-f]+.txt\$") do={ /file/remove [find where name=$oldLog] }
    /file/remove $oldLock
}
:local token [:rndstr from="0123456789abcdef" length=32]
:local logPath ("mikrowarp-operation-" . $token . ".txt")
:local lock {"format"="mikrowarp-lock-v1";"token"=$token;"job"="";"started"="";"created"=[:tostr [:timestamp]];"log"=$logPath}
# File creation is the cross-user mutex; a competing add must fail.
/file/add name=$lockPath type=file contents=[:serialize to=json value=$lock options=json.no-string-conversion]
:global mikrowarpNativeInput
:set mikrowarpNativeInput {"action"=$action;"options"=$options;"token"=$token;"log"=$logPath}
:local job [:execute {
@@WORKER@@
}]
:set ($lock->"job") [:tostr $job]
:local stamp [:tostr [/system/script/job/get $job started]]
:set ($lock->"started") $stamp
/file/set [find where name=$lockPath] contents=[:serialize to=json value=$lock options=json.no-string-conversion]
:local shown 0
:while ([$alive job=$job started=$stamp]) do={
    :delay 1s
    :local file [/file/find where name=$logPath]
    :if ([:len $file] > 0) do={
        :local output [/file/get $file contents]
        :if ([:len $output] < $shown) do={ :set shown 0 }
        :if ([:len $output] > $shown) do={ :put [:pick $output $shown [:len $output]]; :set shown [:len $output] }
    }
}
:local output ""
:if ([:len [/file/find where name=$logPath]] > 0) do={ :set output [/file/get [find where name=$logPath] contents] }
:if ([:len $output] > $shown) do={ :put [:pick $output $shown [:len $output]] }
:local current [/file/find where name=$lockPath]
:if ([:len $current] > 0) do={
    :local record [:deserialize from=json value=[/file/get $current contents] options=json.no-string-conversion]
    :if (($record->"token") = $token) do={ /file/remove $current }
}
# Keep one useful operation log, removing only the previously recorded owned log.
:local last [/file/find where name="mikrowarp-last-operation.txt"]
:if ([:len $last] > 0) do={
    :if ([:pick [/file/get $last contents] 0 [:len "# MikroWARP\n"]] = "# MikroWARP\n") do={ /file/remove $last }
}
:if ([:len [/file/find where name="mikrowarp-last-operation.txt"]] = 0) do={
    :if ([:len [/file/find where name=$logPath]] > 0) do={ /file/set [find where name=$logPath] name="mikrowarp-last-operation.txt"; :set logPath "mikrowarp-last-operation.txt" }
} else={
    # An unrelated file owns the preferred log name; retain no temporary log.
    /file/remove [find where name=$logPath]
    :set logPath "terminal output above"
}
:if ([:typeof [:find $output "RESULT success"]] = "nil") do={ :error ("MikroWARP did not finish. Details: " . $logPath . ". Re-import to resume, or select abort.") }
