# MikroWARP native installer. Generated by standard/routeros/build.py.
# RouterOS 7.23+, x86-64 CHR. Container package/device mode are prerequisites.
# Re-import to resume. No scheduler or installed System script is created.
:global mikrowarpAction
:global mikrowarpOptions
:local action $mikrowarpAction
:local options $mikrowarpOptions
:set mikrowarpAction
:set mikrowarpOptions
:if ([:typeof $action] = "nothing") do={ :set action "apply" }
:if ([:typeof $options] = "nothing") do={ :set options [:toarray ""] }
:if (($action != "apply") && ($action != "status") && ($action != "rollback") && ($action != "abort")) do={ :error "MikroWARP: action must be status, rollback, abort, or unset" }
:if ([:typeof $options] != "array") do={ :error "MikroWARP: mikrowarpOptions must be an array" }
:local version [/system/resource/get version]
:local major [:tonum [:pick $version 0 [:find $version "."]]]
:local rest [:pick $version ([:find $version "."] + 1) [:len $version]]
:local digits ""
:for i from=0 to=([:len $rest] - 1) do={
    :local c [:pick $rest $i ($i + 1)]
    :if (([:len $digits] = $i) && ($c ~ "^[0-9]\$")) do={ :set digits ($digits . $c) }
}
:local minor [:tonum $digits]
:if (($major != 7) || ([:typeof $minor] != "num") || ($minor < 23)) do={ :error "MikroWARP requires RouterOS 7.23 or newer in the v7 series" }
:if ([/system/resource/get architecture-name] != "x86_64") do={ :error "MikroWARP Standard currently supports x86-64 CHR only" }

:local alive do={
    :local yes false
    :do { :if ([:tostr [/system/script/job/get $job started]] = $started) do={ :set yes true } } on-error={}
    :return $yes
}
:local lockPath "mikrowarp-operation.lock.json"
:local oldLock [/file/find where name=$lockPath]
:if ([:len $oldLock] > 0) do={
    :local lock [:deserialize from=json value=[/file/get $oldLock contents] options=json.no-string-conversion]
    :if (($lock->"format") != "mikrowarp-lock-v1") do={ :error "MikroWARP: lock filename is occupied by an unrelated file" }
    :if ([$alive job=($lock->"job") started=($lock->"started")]) do={ :error "MikroWARP: another operation is running; let it finish before importing again" }
    :if ((($lock->"job") = "") && (([:timestamp] - [:totime ($lock->"created")]) < 10s)) do={ :error "MikroWARP: another import is starting; retry in ten seconds" }
    # Recheck a stale claim immediately before removing it; another importer
    # may already have reclaimed the same filename while this one was parsing.
    :local latest [:deserialize from=json value=[/file/get $oldLock contents] options=json.no-string-conversion]
    :if ((($latest->"token") != ($lock->"token")) || [$alive job=($latest->"job") started=($latest->"started")]) do={ :error "MikroWARP: another import claimed the operation; retry after it finishes" }
    :local oldLog ($lock->"log")
    :if ($oldLog ~ "^mikrowarp-operation-[0-9a-f]+.txt\$") do={ /file/remove [find where name=$oldLog] }
    /file/remove $oldLock
}
:local token [:rndstr from="0123456789abcdef" length=32]
:local logPath ("mikrowarp-operation-" . $token . ".txt")
:local lock {"format"="mikrowarp-lock-v1";"token"=$token;"job"="";"started"="";"created"=[:tostr [:timestamp]];"log"=$logPath}
# File creation is the cross-user mutex; a competing add must fail.
/file/add name=$lockPath type=file contents=[:serialize to=json value=$lock options=json.no-string-conversion]
:global mikrowarpNativeInput
:set mikrowarpNativeInput {"action"=$action;"options"=$options;"token"=$token;"log"=$logPath}
:local job [:execute {
# Functions live only for this import job; no System script is installed.
:global mikrowarpNativeInput
:local input $mikrowarpNativeInput
:local action ($input->"action")
:global mikrowarpNativeConfig
:global mikrowarpNativeState
:global mikrowarpNativeRelease
:set mikrowarpNativeRelease {"image_id"="f54570f4b9ede63f337640053a4daccf5da70d0cdfe04f2330ecebaf26a93f39";"sha256"="abb7dd5220e38d146185455b7427c019337d0e83e983bf0e37929febd3193da1";"archive_bytes"=93635286;"logical_bytes"=264691612;"url"="https://github.com/parhamfa/mikrowarp/releases/download/r14-standard/mikrowarp-standard-r14-linux-amd64.tar.gz";"revision"="r14-standard"}
:global mikrowarpNativeLog do={
    :global mikrowarpNativeInput
    :local path ($mikrowarpNativeInput->"log")
    :local old ""
    :local id [/file/find where name=$path]
    :if ([:len $id] > 0) do={ :set old [/file/get $id contents] }
    :if ([:len $old] > 14000) do={ :set old ("# MikroWARP\n" . [:pick $old ([:len $old] - 10000) [:len $old]]) }
    :if ([:len $id] = 0) do={ /file/add name=$path type=file contents=("# MikroWARP\n" . $text . "\n") } else={ /file/set $id contents=($old . $text . "\n") }
}
:global mikrowarpNativeWrite do={
    :local id [/file/find where name=$path]
    :if ([:len $id] = 0) do={ /file/add name=$path type=file contents=$text } else={ /file/set $id contents=$text }
    :if ([/file/get [find where name=$path] contents] != $text) do={ :error "Persistent file readback failed" }
}
:global mikrowarpNativeRead do={
    :local id [/file/find where name=$path]
    :if ([:len $id] = 0) do={ :return "" }
    :return [/file/get $id contents]
}
:global mikrowarpNativeMkdir do={
    :local current ""
    :local remaining $path
    :while ([:len $remaining] > 0) do={
        :local slash [:find $remaining "/"]
        :local part $remaining
        :if ([:typeof $slash] != "nil") do={ :set part [:pick $remaining 0 $slash]; :set remaining [:pick $remaining ($slash + 1) [:len $remaining]] } else={ :set remaining "" }
        :if ($current = "") do={ :set current $part } else={ :set current ($current . "/" . $part) }
        :local id [/file/find where name=$current]
        :if ([:len $id] = 0) do={ /file/add name=$current type=directory } else={
            :local kind [/file/get $id type]
            :if (($kind != "directory") && ($kind != "disk")) do={ :error ("Not a storage directory: " . $current) }
        }
    }
}
# FNV-1a detects torn journal writes; this is not an authentication signature.
:global mikrowarpNativeChecksum do={
    :local hex [:convert $text to=hex]
    :local value 2166136261
    :for i from=0 to=([:len $hex] - 2) step=2 do={ :set value ((($value ^ [:tonum ("0x" . [:pick $hex $i ($i + 2)])]) * 16777619) & 4294967295) }
    :return $value
}
:global mikrowarpNativeBundleCheck do={
    :if ([:len $bundle] = 0) do={ :return true }
    :if ([:typeof $bundle] != "array") do={ :error "Invalid saved release metadata" }
    :foreach key in={"image_id";"sha256"} do={
        :local digest ($bundle->$key)
        :if (([:len $digest] != 64) || !($digest ~ "^[0-9a-f]+\$")) do={ :error "Invalid saved image digest" }
    }
    :foreach key in={"archive_bytes";"logical_bytes"} do={
        :local count ($bundle->$key)
        :if (([:typeof $count] != "num") || ($count < 1) || ($count > 4294967296)) do={ :error "Invalid saved image size" }
    }
    :if (!(($bundle->"revision") ~ "^[A-Za-z0-9._-]+\$") || ([:pick ($bundle->"url") 0 8] != "https://")) do={ :error "Invalid saved release URL or revision" }
    :return true
}
:global mikrowarpNativeRecordCheck do={
    :global mikrowarpNativeBundleCheck
    :if (([:typeof ($record->"sequence")] != "num") || (($record->"sequence") < 0)) do={ :error "Invalid journal sequence" }
    :local phases {"empty";"staging";"quiescing";"switching";"validating-install";"validating";"committing";"complete";"aborting";"aborted"}
    :if ([:typeof [:find $phases ($record->"phase")]] = "nil") do={ :error "Unknown operation phase" }
    :foreach key in={"current";"old";"new"} do={ $mikrowarpNativeBundleCheck bundle=($record->$key) }
    :foreach key in={"snapshot";"restore"} do={
        :local label ($record->$key)
        :if (([:len $label] > 0) && (([:len $label] != 64) || !($label ~ "^[0-9a-f]+\$"))) do={ :error "Invalid state snapshot label" }
    }
    :foreach key in={"previous";"formerPrevious"} do={
        :local previous ($record->$key)
        :if ([:len $previous] > 0) do={
            $mikrowarpNativeBundleCheck bundle=($previous->"bundle")
            :local label ($previous->"snapshot")
            :if (([:len $label] != 64) || !($label ~ "^[0-9a-f]+\$")) do={ :error "Invalid previous state snapshot" }
        }
    }
    :return true
}
:global mikrowarpNativeSave do={
    :global mikrowarpNativeConfig; :global mikrowarpNativeState
    :global mikrowarpNativeChecksum; :global mikrowarpNativeWrite; :global mikrowarpNativeLog; :global mikrowarpNativeMkdir; :global mikrowarpNativeLive; :global mikrowarpNativeRun
    :set ($mikrowarpNativeState->"sequence") (($mikrowarpNativeState->"sequence") + 1)
    :set ($mikrowarpNativeState->"phase") $phase
    :local payload [:serialize to=json value=$mikrowarpNativeState options=json.no-string-conversion]
    :local envelope {"format"="mikrowarp-journal-v1";"payload"=$payload;"checksum"=[$mikrowarpNativeChecksum text=$payload]}
    :local leaf ("operation." . (($mikrowarpNativeState->"sequence") % 2) . ".json")
    $mikrowarpNativeMkdir path=(($mikrowarpNativeConfig->"directory") . "/data/installer")
    $mikrowarpNativeWrite path=(($mikrowarpNativeConfig->"directory") . "/data/installer/" . $leaf) text=[:serialize to=json value=$envelope options=json.no-string-conversion]
    # The existing runtime already provides fsync. Flush the journal before any
    # update cutover, without adding a program or mount to the Standard image.
    :if ([$mikrowarpNativeLive itemName="mikrowarp"]) do={
        $mikrowarpNativeRun itemName="mikrowarp" command=("/usr/local/libexec/mikrowarp-io sync /var/lib/mikrowarp/installer/" . $leaf . " /var/lib/mikrowarp/installer")
    } else={
        # Before first boot there is no runtime fsync helper yet.
        $mikrowarpNativeLog text="Saving progress before continuing (45 seconds)."
        :delay 45s
    }
    $mikrowarpNativeLog text=("Phase: " . $phase)
}
:global mikrowarpNativeComment do={
    :global mikrowarpNativeConfig
    :return ("MikroWARP | " . $purpose . " [" . ($mikrowarpNativeConfig->"owner") . "]")
}
:global mikrowarpNativeQuote do={
    :local result "\""
    :for i from=0 to=([:len $value] - 1) do={
        :local c [:pick $value $i ($i + 1)]
        :if (($c = "\\") || ($c = "\"") || ($c = "\$")) do={ :set result ($result . "\\") }
        :set result ($result . $c)
    }
    :return ($result . "\"")
}
:global mikrowarpNativeEnsure do={
    :global mikrowarpNativeQuote
    :local query [:parse (":return [" . $menu . "/print as-value where " . $selector . "]")]
    :local found [$query]
    :if ([:len $found] > 1) do={ :error ("Ambiguous object: " . $menu) }
    :if ([:len $found] = 1) do={
        :local row [:pick $found 0]
        :foreach key,value in=$properties do={
            :local actual ($row->$key)
            :if ([:typeof $actual] = "bool") do={ :if ($actual) do={ :set actual "yes" } else={ :set actual "no" } }
            :if ([:typeof $actual] = "array") do={ :set actual [:tostr $actual] }
            :if (($key = "src") || ($key = "dst")) do={
                :if ([:pick $actual 0 1] = "/") do={ :set actual [:pick $actual 1 [:len $actual]] }
                :if ([:pick $value 0 1] = "/") do={ :set value [:pick $value 1 [:len $value]] }
            }
            :if (([:tostr $actual] != [:tostr $value]) && !(($key = "src-address") && (([:tostr $actual] . "/32") = $value))) do={ :error ("Existing object differs: " . $menu . " " . $key) }
        }
        :return ($row->".id")
    }
    :local command ($menu . "/add")
    :foreach key,value in=$properties do={ :set command ($command . " " . $key . "=" . [$mikrowarpNativeQuote value=[:tostr $value]]) }
    :local add [:parse $command]; $add
    :local row [:pick [$query] 0]
    :return ($row->".id")
}
:global mikrowarpNativeContainer do={
    :global mikrowarpNativeComment
    :local ids [/container/find where name=$itemName]
    :if ([:len $ids] > 1) do={ :error ("Ambiguous container: " . $itemName) }
    :if ([:len $ids] = 0) do={ :return "" }
    :local id [:pick $ids 0]
    :if ([/container/get $id comment] != [$mikrowarpNativeComment purpose=("Standard " . [:pick ($bundle->"image_id") 0 12])]) do={ :error ("Unowned container: " . $itemName) }
    :return $id
}
:global mikrowarpNativeStopped do={
    :if ([:len [/container/find where name=$itemName]] = 0) do={ :return true }
    :local row [:pick [/container/print as-value where name=$itemName] 0]
    :return (($row->"stopped") || ($row->"download/extract failed"))
}
:global mikrowarpNativeLive do={
    :local rows [/container/print as-value where name=$itemName]
    :if ([:len $rows] != 1) do={ :return false }
    :local row [:pick $rows 0]
    :return (($row->"running") || ($row->"healthy") || ($row->"unhealthy") || ($row->"starting-with-healthcheck"))
}
:global mikrowarpNativeShell do={
    :global mikrowarpNativeConfig; :global mikrowarpNativeInput
    :local id [/container/find where name=$itemName]
    :if ([:len $id] != 1) do={ :error "Container is missing" }
    :local leaf ("router-result-" . ($mikrowarpNativeInput->"token") . ".txt")
    :local resultPath (($mikrowarpNativeConfig->"directory") . "/data/" . $leaf)
    /file/remove [find where name=$resultPath]
    :local script ("(" . $command . ") > /var/lib/mikrowarp/" . $leaf . ".out 2>&1; rc=\$?; { printf '%s\\n' \"\$rc\"; head -c 12000 /var/lib/mikrowarp/" . $leaf . ".out; } > /var/lib/mikrowarp/" . $leaf . "; rm -f /var/lib/mikrowarp/" . $leaf . ".out")
    /container/shell $id cmd=$script
    # File-menu visibility can lag a container's write. Wait for the complete
    # result instead of treating a visibility delay as a failed container boot.
    :local file ""; :local result ""
    :for i from=1 to=20 do={
        :if ([:len $result] = 0) do={
            :set file [/file/find where name=$resultPath]
            :if ([:len $file] > 0) do={ :set result [/file/get $file contents] }
            :if ([:len $result] = 0) do={ :delay 250ms }
        }
    }
    :if ([:len $result] = 0) do={ :error "Container command did not return a result; re-import to resume" }
    /file/remove $file
    :local newline [:find $result "\n"]
    :if ([:typeof $newline] = "nil") do={ :error "Incomplete container result" }
    :local code [:tonum [:pick $result 0 $newline]]
    :if (([:typeof $code] != "num") || ($code < 0) || ($code > 255)) do={ :error "Invalid container command result" }
    :return {"code"=$code;"output"=[:pick $result ($newline + 1) [:len $result]]}
}
:global mikrowarpNativeRun do={
    :global mikrowarpNativeShell
    :local result [$mikrowarpNativeShell itemName=$itemName command=$command]
    :if (($result->"code") != 0) do={ :error ("Container operation failed: " . ($result->"output")) }
    :return ($result->"output")
}
:global mikrowarpNativeReady do={
    :global mikrowarpNativeShell
    :local ready false
    :do { :local result [$mikrowarpNativeShell itemName="mikrowarp" command="/usr/local/sbin/mikrowarp"]; :set ready (($result->"code") = 0) } on-error={}
    :return $ready
}
:global mikrowarpNativeAccept do={
    :global mikrowarpNativeReady; :global mikrowarpNativeRun
    :local ok false
    :local deadline ([:timestamp] + 7m)
    :while ((!$ok) && ([:timestamp] < $deadline)) do={ :set ok [$mikrowarpNativeReady]; :if (!$ok) do={ :delay 5s } }
    :if (!$ok) do={ :error "WARP forwarding did not become healthy within seven minutes" }
    $mikrowarpNativeRun itemName="mikrowarp" command="cd /; sha256sum -c /usr/share/mikrowarp/warp-binaries.sha256"
}

:global mikrowarpNativeSpace do={
    :global mikrowarpNativeConfig
    :local path ($mikrowarpNativeConfig->"directory")
    :local free [/system/resource/get free-hdd-space]
    :foreach disk in=[/disk/print as-value] do={
        :local mount ($disk->"mount-point")
        :if (([:len $mount] > 0) && (($path = $mount) || ([:pick $path 0 ([:len $mount] + 1)] = ($mount . "/")))) do={ :set free ($disk->"free") }
    }
    :return $free
}
:global mikrowarpNativeDownload do={
    :global mikrowarpNativeConfig; :global mikrowarpNativeMkdir; :global mikrowarpNativeSpace; :global mikrowarpNativeLog
    :local base ($mikrowarpNativeConfig->"directory")
    :local path ($base . "/archives/" . ($bundle->"sha256") . ".tar.gz")
    :local existing [/file/find where name=$path]
    :local need ((2 * ($bundle->"logical_bytes")) + 268435456)
    :if ([:len $existing] > 0) do={
        :if ([/file/get $existing size] != ($bundle->"archive_bytes")) do={ :error "Saved image has the wrong size; it has been retained for inspection" }
        :if ([$mikrowarpNativeSpace] < $need) do={ :error ("Insufficient staging space: need " . $need . " free bytes with the archive already present") }
        :return $path
    }
    :set need ($need + ($bundle->"archive_bytes"))
    :if ([$mikrowarpNativeSpace] < $need) do={ :error ("Insufficient staging space: need " . $need . " free bytes") }
    $mikrowarpNativeMkdir path=($base . "/archives")
    :local partial ($path . ".partial")
    /file/remove [find where name=$partial]
    $mikrowarpNativeLog text=("Downloading " . ($bundle->"revision") . " (" . ($bundle->"archive_bytes") . " bytes)")
    :onerror err in={
        /tool/fetch url=($bundle->"url") dst-path=$partial check-certificate=yes http-max-redirect-count=5 idle-timeout=30s duration=30m
        :if ([/file/get [find where name=$partial] size] != ($bundle->"archive_bytes")) do={ :error "Download size does not match release metadata" }
        /file/set [find where name=$partial] name=$path
    } do={ /file/remove [find where name=$partial]; :error ("Download failed; re-import to retry. " . $err) }
    :return $path
}
:global mikrowarpNativeImport do={
    :global mikrowarpNativeConfig; :global mikrowarpNativeContainer; :global mikrowarpNativeMkdir; :global mikrowarpNativeComment; :global mikrowarpNativeLog; :global mikrowarpNativeLive; :global mikrowarpNativeRemove
    :local id [$mikrowarpNativeContainer itemName=$itemName bundle=$bundle]
    :local created false
    :if (($id != "") && ![$mikrowarpNativeLive itemName=$itemName]) do={
        # After a reboot, an extraction may look complete while its last writes
        # were lost. Rebuild a stopped candidate from the retained archive.
        :local extracting true
        :for i from=1 to=180 do={
            :if ($extracting) do={
                :local row [:pick [/container/print as-value where name=$itemName] 0]
                :set extracting (($row->"extracting") || ($row->"downloading") || ($row->"downloading/extracting"))
                :if ($extracting) do={ :delay 5s }
            }
        }
        :if ($extracting) do={ :error "Extraction is still running; re-import when it finishes" }
        $mikrowarpNativeRemove itemName=$itemName bundle=$bundle
        :set id ""
    }
    :if ($id = "") do={
        :set created true
        $mikrowarpNativeRemove itemName=$itemName bundle=$bundle
        :local release (($mikrowarpNativeConfig->"directory") . "/releases/" . [:pick ($bundle->"image_id") 0 16])
        $mikrowarpNativeMkdir path=$release
        $mikrowarpNativeLog text=("Importing stopped image: " . $itemName)
        /container/add name=$itemName file=$archive interface=mikrowarp-veth root-dir=($release . "/root") layer-dir=($release . "/layers") envlists=mikrowarp mountlists=mikrowarp dns=1.1.1.1 user=0:0 logging=yes start-on-boot=no restart-policy=always restart-interval=10s comment=[$mikrowarpNativeComment purpose=("Standard " . [:pick ($bundle->"image_id") 0 12])]
    }
    :local done false
    :for i from=1 to=180 do={
        :if (!$done) do={
            :set id [$mikrowarpNativeContainer itemName=$itemName bundle=$bundle]
            :local row [:pick [/container/print as-value where name=$itemName] 0]
            :if (($row->"error") || ($row->"failed") || ($row->"download/extract failed")) do={ :error "Container image extraction failed" }
            :if (!(($row->"extracting") || ($row->"downloading") || ($row->"downloading/extracting"))) do={
                :if ([/container/get $id image-id] != ($bundle->"image_id")) do={ :error "Imported image ID does not match the pinned release" }
                :set done true
            } else={ :delay 5s }
        }
    }
    :if (!$done) do={ :error "Image extraction is still pending; re-import to resume" }
    :if ($created) do={
        $mikrowarpNativeLog text="Allowing extracted image writes to settle before cutover (45 seconds)."
        :delay 45s
    }
    :return $id
}
:global mikrowarpNativeStop do={
    :global mikrowarpNativeContainer; :global mikrowarpNativeStopped
    :local id [$mikrowarpNativeContainer itemName=$itemName bundle=$bundle]
    :if ($id = "") do={ :return true }
    :if (![$mikrowarpNativeStopped itemName=$itemName]) do={ /container/stop $id }
    :local stopped false
    :for i from=1 to=60 do={ :if (!$stopped) do={ :set stopped [$mikrowarpNativeStopped itemName=$itemName]; :if (!$stopped) do={ :delay 2s } } }
    :if (!$stopped) do={ :error ("Container did not stop: " . $itemName) }
    # Also cancel a restart already queued by a candidate that exits immediately.
    :if ([/container/get $id start-on-boot] || ([/container/get $id restart-policy] != "no")) do={ /container/set $id start-on-boot=no restart-policy=no }
}
:global mikrowarpNativeStart do={
    :global mikrowarpNativeContainer; :global mikrowarpNativeStopped; :global mikrowarpNativeStop; :global mikrowarpNativeShell
    :local id [$mikrowarpNativeContainer itemName=$itemName bundle=$bundle]
    :if ($id = "") do={ :error "Missing container during start" }
    :if ((![/container/get $id start-on-boot]) || ([/container/get $id restart-policy] != "always")) do={
        :if (![$mikrowarpNativeStopped itemName=$itemName]) do={ $mikrowarpNativeStop itemName=$itemName bundle=$bundle }
        /container/set $id start-on-boot=yes restart-policy=always restart-interval=10s
    }
    :if ([$mikrowarpNativeStopped itemName=$itemName]) do={ /container/start $id }
    :local available false
    :local lastError "Container boot is not initialized"
    :local deadline ([:timestamp] + 2m)
    :while ((!$available) && ([:timestamp] < $deadline)) do={
        :onerror err in={ :local r [$mikrowarpNativeShell itemName=$itemName command="test -r /run/mikrowarp/runtime.env"]; :set available (($r->"code") = 0) } do={ :set lastError $err }
        :if (!$available) do={ :delay 2s }
    }
    :if (!$available) do={ :error ("Container command interface did not become ready: " . $lastError) }
}
:global mikrowarpNativeRename do={
    :global mikrowarpNativeContainer; :global mikrowarpNativeStopped
    :if ([:len [/container/find where name=$target]] > 0) do={ :error "Container rename target is occupied" }
    :local id [$mikrowarpNativeContainer itemName=$source bundle=$bundle]
    :if (($id = "") || (![$mikrowarpNativeStopped itemName=$source])) do={ :error "Rename requires a stopped owned container" }
    /container/set $id name=$target
}
:global mikrowarpNativeRemove do={
    :global mikrowarpNativeContainer; :global mikrowarpNativeStopped; :global mikrowarpNativeConfig
    :local id [$mikrowarpNativeContainer itemName=$itemName bundle=$bundle]
    :if ($id != "") do={
        :if (![$mikrowarpNativeStopped itemName=$itemName]) do={ :error "Refusing to remove a running container" }
        /container/remove $id
        :local removed false
        :for i from=1 to=90 do={ :if (!$removed) do={ :set removed ([:len [/container/find where name=$itemName]] = 0); :if (!$removed) do={ :delay 2s } } }
        :if (!$removed) do={ :error "Container removal is still pending" }
    }
    :local release (($mikrowarpNativeConfig->"directory") . "/releases/" . [:pick ($bundle->"image_id") 0 16])
    # Layer/root cleanup must never affect another container referencing this release.
    :local used false
    :foreach c in=[/container/print as-value] do={ :if ([:typeof [:find ($c->"root-dir") ($release . "/")]] != "nil") do={ :set used true } }
    :foreach layer in=[/container/layers/print as-value] do={
        :local directory [:tostr ($layer->"layer-dir")]
        :if (([:len ($layer->"containers")] > 0) && ([:typeof [:find ($directory . "/") ($release . "/")]] != "nil")) do={ :set used true }
    }
    :if (!$used) do={
        # RouterOS may release the container row before finishing directory GC.
        :for i from=1 to=60 do={
            :local files [/file/find where name=$release]
            :if ([:len $files] > 0) do={ :do { /file/remove $files } on-error={}; :if ([:len [/file/find where name=$release]] > 0) do={ :delay 2s } }
        }
        :if ([:len [/file/find where name=$release]] > 0) do={ :error "Release directory cleanup is still pending; re-import to resume" }
    }
}
:global mikrowarpNativeCommit do={
    :global mikrowarpNativeConfig; :global mikrowarpNativeState; :global mikrowarpNativeSave; :global mikrowarpNativeRemove; :global mikrowarpNativeRun
    :local old ($mikrowarpNativeState->"old"); :local new ($mikrowarpNativeState->"new")
    :local former ($mikrowarpNativeState->"formerPrevious")
    :set ($mikrowarpNativeState->"current") $new
    :set ($mikrowarpNativeState->"previous") {"bundle"=$old;"snapshot"=($mikrowarpNativeState->"snapshot")}
    $mikrowarpNativeSave phase="committing"
    $mikrowarpNativeRemove itemName="mikrowarp-old" bundle=$old
    :if ([:len ($former->"snapshot")] > 0) do={
        :local obsolete ($former->"bundle")
        :if ((($obsolete->"sha256") != ($old->"sha256")) && (($obsolete->"sha256") != ($new->"sha256"))) do={ /file/remove [find where name=(($mikrowarpNativeConfig->"directory") . "/archives/" . ($obsolete->"sha256") . ".tar.gz")] }
        :local label ($former->"snapshot")
        :if (([:len $label] = 64) && ($label ~ "^[0-9a-f]+\$") && ($label != ($mikrowarpNativeState->"snapshot"))) do={ $mikrowarpNativeRun itemName="mikrowarp" command=("rm -f /var/lib/mikrowarp/recovery/" . $label . ".tar /var/lib/mikrowarp/recovery/" . $label . ".tar.sha256") }
    }
    $mikrowarpNativeSave phase="complete"
}
:global mikrowarpNativeAbort do={
    :global mikrowarpNativeState; :global mikrowarpNativeConfig; :global mikrowarpNativeSave; :global mikrowarpNativeWrite
    :global mikrowarpNativeStop; :global mikrowarpNativeRemove; :global mikrowarpNativeRename; :global mikrowarpNativeStart; :global mikrowarpNativeImport; :global mikrowarpNativeRun; :global mikrowarpNativeLog
    :if (($mikrowarpNativeState->"phase") = "committing") do={ :error "Commit has started; re-import to finish before selecting rollback" }
    :local old ($mikrowarpNativeState->"old"); :local new ($mikrowarpNativeState->"new")
    :local base ($mikrowarpNativeConfig->"directory")
    $mikrowarpNativeSave phase="aborting"
    :if (($mikrowarpNativeState->"kind") = "install") do={
        $mikrowarpNativeStop itemName="mikrowarp" bundle=$new
        $mikrowarpNativeSave phase="aborted"
        $mikrowarpNativeLog text="Installation stopped. Owned files and registration are retained; re-import to retry."
        :return true
    }
    :if ($mikrowarpNativeState->"snapshotCreated") do={ $mikrowarpNativeWrite path=($base . "/data/maintenance.lock") text="administrator_operation" }
    :local id [/container/find where name="mikrowarp"]
    :if ([:len $id] > 0) do={
        :if ([/container/get $id image-id] = ($new->"image_id")) do={ $mikrowarpNativeStop itemName="mikrowarp" bundle=$new; $mikrowarpNativeRemove itemName="mikrowarp" bundle=$new }
    }
    :if ([:len [/container/find where name="mikrowarp"]] = 0) do={
        :if ([:len [/container/find where name="mikrowarp-old"]] > 0) do={ $mikrowarpNativeRename source="mikrowarp-old" target="mikrowarp" bundle=$old } else={ $mikrowarpNativeImport itemName="mikrowarp" bundle=$old archive=($base . "/archives/" . ($old->"sha256") . ".tar.gz") }
    }
    $mikrowarpNativeStart itemName="mikrowarp" bundle=$old
    :if ($mikrowarpNativeState->"snapshotCreated") do={
        $mikrowarpNativeRun itemName="mikrowarp" command="/usr/local/sbin/mikrowarp maintenance begin"
        $mikrowarpNativeRun itemName="mikrowarp" command=("/usr/local/sbin/mikrowarp maintenance restore " . ($mikrowarpNativeState->"snapshot"))
    }
    $mikrowarpNativeRun itemName="mikrowarp" command="/usr/local/sbin/mikrowarp maintenance resume"
    $mikrowarpNativeStop itemName="mikrowarp-next" bundle=$new
    $mikrowarpNativeRemove itemName="mikrowarp-next" bundle=$new
    :set ($mikrowarpNativeState->"current") $old
    :set ($mikrowarpNativeState->"previous") ($mikrowarpNativeState->"formerPrevious")
    :local previousBundle (($mikrowarpNativeState->"previous")->"bundle")
    :if ((($new->"sha256") != ($old->"sha256")) && (($new->"sha256") != ($previousBundle->"sha256"))) do={ /file/remove [find where name=($base . "/archives/" . ($new->"sha256") . ".tar.gz")] }
    :if ($mikrowarpNativeState->"snapshotCreated") do={
        :local label ($mikrowarpNativeState->"snapshot")
        $mikrowarpNativeRun itemName="mikrowarp" command=("rm -f /var/lib/mikrowarp/recovery/" . $label . ".tar /var/lib/mikrowarp/recovery/" . $label . ".tar.sha256")
    }
    $mikrowarpNativeSave phase="aborted"
    $mikrowarpNativeLog text="Previous image and matching state restored; ordinary WARP recovery is active."
}
:global mikrowarpNativeResume do={
    :global mikrowarpNativeState; :global mikrowarpNativeConfig; :global mikrowarpNativeSave; :global mikrowarpNativeDownload
    :global mikrowarpNativeImport; :global mikrowarpNativeStart; :global mikrowarpNativeRun; :global mikrowarpNativeStop; :global mikrowarpNativeRename; :global mikrowarpNativeAccept; :global mikrowarpNativeCommit; :global mikrowarpNativeAbort; :global mikrowarpNativeLog
    :if (($mikrowarpNativeState->"phase") = "aborting") do={ $mikrowarpNativeAbort; :return true }
    :if (($mikrowarpNativeState->"phase") = "committing") do={ $mikrowarpNativeCommit; :return true }
    :local old ($mikrowarpNativeState->"old"); :local new ($mikrowarpNativeState->"new")
    :local archive [$mikrowarpNativeDownload bundle=$new]
    :if (($mikrowarpNativeState->"kind") = "install") do={
        $mikrowarpNativeImport itemName="mikrowarp" bundle=$new archive=$archive
        $mikrowarpNativeStart itemName="mikrowarp" bundle=$new
        $mikrowarpNativeSave phase="validating-install"
        $mikrowarpNativeLog text="Waiting for forwarded WARP HTTPS and UDP DNS health."
        $mikrowarpNativeAccept
        :set ($mikrowarpNativeState->"current") $new
        $mikrowarpNativeSave phase="complete"
        :return true
    }
    :local current [/container/find where name="mikrowarp"]
    :if ([:len $current] > 0) do={
        :if ([/container/get $current image-id] = ($old->"image_id")) do={
            $mikrowarpNativeImport itemName="mikrowarp-next" bundle=$new archive=$archive
            $mikrowarpNativeSave phase="quiescing"
            $mikrowarpNativeStart itemName="mikrowarp" bundle=$old
            $mikrowarpNativeRun itemName="mikrowarp" command="/usr/local/sbin/mikrowarp maintenance begin"
            $mikrowarpNativeRun itemName="mikrowarp" command=("/usr/local/sbin/mikrowarp maintenance snapshot " . ($mikrowarpNativeState->"snapshot"))
            :set ($mikrowarpNativeState->"snapshotCreated") true
            $mikrowarpNativeSave phase="switching"
            $mikrowarpNativeStop itemName="mikrowarp" bundle=$old
            $mikrowarpNativeRename source="mikrowarp" target="mikrowarp-old" bundle=$old
        }
    }
    :if ([:len [/container/find where name="mikrowarp"]] = 0) do={ $mikrowarpNativeRename source="mikrowarp-next" target="mikrowarp" bundle=$new }
    :onerror err in={
        $mikrowarpNativeStart itemName="mikrowarp" bundle=$new
        :if (([:len ($mikrowarpNativeState->"restore")] > 0) && (($mikrowarpNativeState->"phase") != "validating")) do={
            $mikrowarpNativeRun itemName="mikrowarp" command="/usr/local/sbin/mikrowarp maintenance begin"
            $mikrowarpNativeRun itemName="mikrowarp" command=("/usr/local/sbin/mikrowarp maintenance restore " . ($mikrowarpNativeState->"restore"))
        }
        $mikrowarpNativeSave phase="validating"
        $mikrowarpNativeRun itemName="mikrowarp" command="/usr/local/sbin/mikrowarp maintenance resume"
        $mikrowarpNativeLog text="Validating candidate forwarding before removing the previous container."
        $mikrowarpNativeAccept
    } do={
        $mikrowarpNativeLog text=("Candidate rejected: " . $err)
        $mikrowarpNativeAbort
        :error "Candidate rejected; previous image and state restored"
    }
    $mikrowarpNativeCommit
}

:global mikrowarpNativeAvailable do={
    :local make [:parse (":return " . $network)]
    :local subnet [$make]
    :local ip [:toip [:pick $network 0 [:find $network "/"]]]
    :foreach address in=[/ip/address/print as-value] do={
        :if (($address->"interface") != "mikrowarp-link") do={
            :local otherMake [:parse (":return " . ($address->"address"))]
            :if (($ip in [$otherMake]) || (($address->"network") in $subnet)) do={ :return false }
        }
    }
    :foreach route in=[/ip/route/print as-value] do={
        :local dst [:tostr ($route->"dst-address")]
        :if (($dst != "0.0.0.0/0") && !((($route->"gateway") = "mikrowarp-link") && ($dst = $network))) do={
            :local otherMake [:parse (":return " . $dst)]
            :local otherIp [:toip [:pick $dst 0 [:find $dst "/"]]]
            :if (($ip in [$otherMake]) || ($otherIp in $subnet)) do={ :return false }
        }
    }
    :return true
}
:global mikrowarpNativeNetwork do={
    :global mikrowarpNativeConfig; :global mikrowarpNativeEnsure; :global mikrowarpNativeComment; :global mikrowarpNativeQuote
    :local c $mikrowarpNativeConfig
    $mikrowarpNativeEnsure menu="/interface/bridge" selector=("name=\"mikrowarp-link\"") properties=({"name"="mikrowarp-link";"protocol-mode"="none";"comment"=[$mikrowarpNativeComment purpose="Transit link"]})
    $mikrowarpNativeEnsure menu="/interface/veth" selector=("name=\"mikrowarp-veth\"") properties=({"name"="mikrowarp-veth";"address"=(($c->"gateway") . "/30");"gateway"=($c->"router");"comment"=[$mikrowarpNativeComment purpose="Gateway"]})
    $mikrowarpNativeEnsure menu="/interface/bridge/port" selector=("interface=\"mikrowarp-veth\"") properties=({"bridge"="mikrowarp-link";"interface"="mikrowarp-veth";"comment"=[$mikrowarpNativeComment purpose="Gateway port"]})
    :local addressComment [$mikrowarpNativeComment purpose="Transit address"]
    $mikrowarpNativeEnsure menu="/ip/address" selector=("comment=" . [$mikrowarpNativeQuote value=$addressComment]) properties=({"address"=(($c->"router") . "/30");"interface"="mikrowarp-link";"comment"=$addressComment})
    :local rules {
        {"menu"="/ip/firewall/nat";"purpose"="Uplink NAT";"properties"={"chain"="srcnat";"src-address"=(($c->"gateway") . "/32");"out-interface"=($c->"uplink");"action"="masquerade"}};
        {"menu"="/ip/firewall/filter";"purpose"="Protect router services";"properties"={"chain"="input";"in-interface"="mikrowarp-link";"connection-state"="invalid,new,untracked";"action"="drop"}};
        {"menu"="/ip/firewall/filter";"purpose"="Allow container uplink";"properties"={"chain"="forward";"in-interface"="mikrowarp-link";"src-address"=(($c->"gateway") . "/32");"out-interface"=($c->"uplink");"action"="accept"}};
        {"menu"="/ip/firewall/filter";"purpose"="Block container initiated LAN access";"properties"={"chain"="forward";"in-interface"="mikrowarp-link";"connection-state"="invalid,new,untracked";"action"="drop"}}
    }
    :local filters [:toarray ""]; :local nat ""
    :foreach rule in=$rules do={
        :local comment [$mikrowarpNativeComment purpose=($rule->"purpose")]
        :local properties ($rule->"properties"); :set ($properties->"comment") $comment
        :local id [$mikrowarpNativeEnsure menu=($rule->"menu") selector=("comment=" . [$mikrowarpNativeQuote value=$comment]) properties=$properties]
        :if (($rule->"menu") = "/ip/firewall/filter") do={ :set filters ($filters,$id) } else={ :set nat $id }
    }
    :if ([:pick [/ip/firewall/nat/find] 0] != $nat) do={ /ip/firewall/nat/move $nat destination=0 }
    :local actual [/ip/firewall/filter/find]
    :if ([:pick $actual 0 3] != $filters) do={ :for i from=2 to=0 step=-1 do={ /ip/firewall/filter/move [:pick $filters $i] destination=0 } }
    $mikrowarpNativeEnsure menu="/container/envs" selector=("list=\"mikrowarp\" and key=\"MIKROWARP_STATE_ID\"") properties=({"list"="mikrowarp";"key"="MIKROWARP_STATE_ID";"value"=($c->"owner")})
    $mikrowarpNativeEnsure menu="/container/mounts" selector=("list=\"mikrowarp\"") properties=({"list"="mikrowarp";"src"=(($c->"directory") . "/data");"dst"="/var/lib/mikrowarp"})
}
:global mikrowarpNativeMain do={
    :global mikrowarpNativeConfig; :global mikrowarpNativeState; :global mikrowarpNativeRelease; :global mikrowarpNativeInput
    :global mikrowarpNativeRead; :global mikrowarpNativeWrite; :global mikrowarpNativeLog; :global mikrowarpNativeChecksum; :global mikrowarpNativeMkdir; :global mikrowarpNativeAvailable; :global mikrowarpNativeNetwork; :global mikrowarpNativeRecordCheck
    :global mikrowarpNativeComment; :global mikrowarpNativeSave; :global mikrowarpNativeResume; :global mikrowarpNativeAbort; :global mikrowarpNativeContainer; :global mikrowarpNativeShell; :global mikrowarpNativeLive
    :local options ($mikrowarpNativeInput->"options")
    :foreach key,value in=$options do={ :if (($key != "network") && ($key != "directory") && ($key != "uplink")) do={ :error ("Unknown option: " . $key) } }
    :local raw [$mikrowarpNativeRead path="mikrowarp-installation.json"]
    :local fresh ($raw = "")
    :if ($fresh && ($action != "apply")) do={ $mikrowarpNativeLog text="MikroWARP has no native installation on this router."; :return true }
    :if ([:len [/system/package/find where name="container" and disabled=no]] != 1) do={ :error "Install the matching RouterOS container package first" }
    :if (![/system/device-mode/get container]) do={ :error "Enable container device mode first; the installer does not reboot the router" }
    :if ($fresh) do={
        :set mikrowarpNativeConfig {"format"="mikrowarp-native-v1";"owner"=[:rndstr from="0123456789abcdef" length=32]}
        :foreach itemName in={"mikrowarp-link";"mikrowarp-veth"} do={ :if ([:len [/interface/find where name=$itemName]] > 0) do={ :error ("Interface name is occupied: " . $itemName) } }
        :foreach itemName in={"mikrowarp";"mikrowarp-next";"mikrowarp-old"} do={ :if ([:len [/container/find where name=$itemName]] > 0) do={ :error ("Container name is occupied: " . $itemName . "; existing installations are not adopted") } }
        :if (([:len [/container/envs/find where list="mikrowarp"]] > 0) || ([:len [/container/mounts/find where list="mikrowarp"]] > 0)) do={ :error "The mikrowarp environment or mount namespace is occupied" }
        :local uplink ($options->"uplink")
        :if ([:len $uplink] = 0) do={
            :local choices [:toarray ""]
            :foreach route in=[/routing/route/print as-value where dst-address="0.0.0.0/0" and routing-table=main and active] do={
                :local gateway [:tostr ($route->"immediate-gw")]
                :if (([:typeof [:find $gateway ","]] != "nil") || ([:typeof [:find $gateway ";"]] != "nil")) do={ :error "Multiple active uplinks; set mikrowarpOptions uplink explicitly" }
                :local mark [:find $gateway "%"]
                :local interface $gateway
                :if ([:typeof $mark] != "nil") do={ :set interface [:pick $gateway ($mark + 1) [:len $gateway]] }
                :if (([:len $interface] > 0) && ([:len [/interface/find where name=$interface]] = 1)) do={ :set ($choices->$interface) true }
            }
            :if ([:len $choices] != 1) do={ :error "Cannot choose one active main-table uplink; set mikrowarpOptions uplink explicitly" }
            :foreach itemName,value in=$choices do={ :set uplink $itemName }
        }
        :if ([:len [/interface/find where name=$uplink]] != 1) do={ :error "The selected uplink does not exist" }
        :set ($mikrowarpNativeConfig->"uplink") $uplink
        :local network ($options->"network")
        :if ([:len $network] = 0) do={
            :foreach pool in={172.31.242.0;10.255.242.0;192.168.242.0} do={
                :for i from=0 to=511 do={
                    :if ([:len $network] = 0) do={
                        :local candidate ([:tostr ($pool + ($i * 4))] . "/30")
                        :if ([$mikrowarpNativeAvailable network=$candidate]) do={ :set network $candidate }
                    }
                }
            }
            :if ([:len $network] = 0) do={ :error "No unused transit subnet found; set mikrowarpOptions network to an unused private /30" }
        }
        :if (!($network ~ "^[0-9]+.[0-9]+.[0-9]+.[0-9]+/30\$")) do={ :error "Transit network must be an IPv4 /30" }
        :local ip [:toip [:pick $network 0 [:find $network "/"]]]
        :if (!(($ip in 10.0.0.0/8) || ($ip in 172.16.0.0/12) || ($ip in 192.168.0.0/16)) || (($ip & 0.0.0.3) != 0.0.0.0)) do={ :error "Use an aligned RFC1918 /30 transit network" }
        :if (![$mikrowarpNativeAvailable network=$network]) do={ :error "Transit network overlaps existing addresses or routes" }
        :set ($mikrowarpNativeConfig->"network") $network
        :set ($mikrowarpNativeConfig->"router") [:tostr ($ip + 1)]
        :set ($mikrowarpNativeConfig->"gateway") [:tostr ($ip + 2)]
        :local need (($mikrowarpNativeRelease->"archive_bytes") + (2 * ($mikrowarpNativeRelease->"logical_bytes")) + 268435456)
        :local directory ($options->"directory")
        :local mount ""
        :if ([:len $directory] = 0) do={
            :if ([/system/resource/get free-hdd-space] >= $need) do={ :set directory "mikrowarp" } else={
                :local most 0
                :foreach disk in=[/disk/print as-value] do={
                    :local point ($disk->"mount-point")
                    :local free ($disk->"free")
                    :if (([:len $point] > 0) && (($disk->"fs") != "tmpfs") && ($free >= $need) && ($free > $most)) do={
                        :local probe ($point . "/mikrowarp-storage-probe.txt")
                        :local writable false
                        :do {
                            :local id [/file/find where name=$probe]
                            :if ([:len $id] > 0) do={ :if ([/file/get $id contents] != "mikrowarp-storage-probe-v1") do={ :error "Probe path occupied" }; /file/remove $id }
                            /file/add name=$probe type=file contents="mikrowarp-storage-probe-v1"
                            :set writable ([/file/get [find where name=$probe] contents] = "mikrowarp-storage-probe-v1")
                            /file/remove [find where name=$probe]
                        } on-error={}
                        :if ($writable) do={ :set directory ($point . "/mikrowarp"); :set mount $point; :set most $free }
                    }
                }
                :if ([:len $directory] = 0) do={ :error ("Not enough writable storage; need " . $need . " free bytes internally or on a mounted disk") }
            }
        }
        :if (!($directory ~ "^[A-Za-z0-9_-]+(/[A-Za-z0-9_-]+)*\$")) do={ :error "Use a simple relative storage directory such as disk1/mikrowarp" }
        :foreach disk in=[/disk/print as-value] do={
            :local point ($disk->"mount-point")
            :if (([:len $point] > 0) && ([:pick $directory 0 ([:len $point] + 1)] = ($point . "/"))) do={
                :if (($disk->"fs") = "tmpfs") do={ :error "Use persistent storage, not a RAM disk" }
                :set mount $point
            }
        }
        :if ([:len [/file/find where name=$directory]] > 0) do={ :error "Storage directory already exists; choose an unused directory" }
        :set ($mikrowarpNativeConfig->"directory") $directory
        :set ($mikrowarpNativeConfig->"mount") $mount
        :global mikrowarpNativeSpace
        :if ([$mikrowarpNativeSpace] < $need) do={ :error "Selected directory does not have enough staging space" }
        $mikrowarpNativeWrite path="mikrowarp-installation.json" text=[:serialize to=json value=$mikrowarpNativeConfig options=json.no-string-conversion]
        # RouterOS can defer internal file writes for up to 40 seconds. Publish
        # the ownership pointer durably before creating anything on another disk.
        $mikrowarpNativeLog text="Saving installation identity before creating router objects (45 seconds)."
        :delay 45s
    } else={ :set mikrowarpNativeConfig [:deserialize from=json value=$raw options=json.no-string-conversion] }
    :local c $mikrowarpNativeConfig
    :if (($c->"format") != "mikrowarp-native-v1") do={ :error "Unknown installation metadata; nothing is adopted automatically" }
    :if (([:len ($c->"owner")] != 32) || !(($c->"owner") ~ "^[0-9a-f]+\$")) do={ :error "Invalid installation ownership record" }
    :if (!(($c->"directory") ~ "^[A-Za-z0-9_-]+(/[A-Za-z0-9_-]+)*\$")) do={ :error "Invalid installation directory" }
    :local net ($c->"network")
    :local addr [:toip [:pick $net 0 [:find $net "/"]]]
    :if (([:typeof $addr] != "ip") || ($net != ([:tostr $addr] . "/30"))) do={ :error "Invalid saved transit network" }
    :if (!(($addr in 10.0.0.0/8) || ($addr in 172.16.0.0/12) || ($addr in 192.168.0.0/16)) || (($addr & 0.0.0.3) != 0.0.0.0)) do={ :error "Invalid saved private transit network" }
    :if ((($c->"router") != [:tostr ($addr + 1)]) || (($c->"gateway") != [:tostr ($addr + 2)])) do={ :error "Saved transit addresses differ from the network" }
    :if ([:len [/interface/find where name=($c->"uplink")]] != 1) do={ :error "The saved uplink is missing" }
    :foreach key,value in=$options do={ :if ([:tostr ($c->$key)] != [:tostr $value]) do={ :error ("Saved " . $key . " differs; installation settings are not changed by re-import") } }
    :if ([:len ($c->"mount")] > 0) do={
        :if (([:len [/disk/find where mount-point=($c->"mount") and mounted]] = 0) || ([:pick ($c->"directory") 0 ([:len ($c->"mount")] + 1)] != (($c->"mount") . "/"))) do={ :error "The installation disk is not mounted at its saved location" }
    }
    :local base ($c->"directory")
    :local owner [$mikrowarpNativeRead path=($base . "/owner.txt")]
    :if (($owner != "") && ($owner != ($c->"owner"))) do={ :error "Storage ownership differs" }
    :if ($owner = "") do={
        :foreach f in=[/file/print as-value] do={ :if ([:pick ($f->"name") 0 ([:len $base] + 1)] = ($base . "/")) do={ :error "Unowned files exist in the selected directory" } }
        $mikrowarpNativeMkdir path=$base
        $mikrowarpNativeWrite path=($base . "/owner.txt") text=($c->"owner")
        $mikrowarpNativeLog text="Saving storage ownership (45 seconds)."
        :delay 45s
    }
    # A reboot can interrupt a shell-result handoff. These reserved temporary
    # files are safe to remove only after validating storage ownership and lock.
    :local resultPrefix ($base . "/data/router-result-")
    :foreach f in=[/file/print as-value] do={
        :local filename ($f->"name")
        :if ([:pick $filename 0 [:len $resultPrefix]] = $resultPrefix) do={
            :local tail [:pick $filename [:len $resultPrefix] [:len $filename]]
            :if ((([:len $tail] = 36) || ([:len $tail] = 40)) && ($tail ~ "^[0-9a-f]+[.]txt([.]out)?\$")) do={ /file/remove ($f->".id") }
        }
    }
    :set mikrowarpNativeState [:toarray ""]
    :local invalid 0
    :for slot from=0 to=1 do={
        :local text [$mikrowarpNativeRead path=($base . "/data/installer/operation." . $slot . ".json")]
        :if ([:len $text] > 0) do={
            :do {
                :local envelope [:deserialize from=json value=$text options=json.no-string-conversion]
                :local payload ($envelope->"payload")
                :if ((($envelope->"format") != "mikrowarp-journal-v1") || ([$mikrowarpNativeChecksum text=$payload] != ($envelope->"checksum"))) do={ :error "Invalid journal slot" }
                :local record [:deserialize from=json value=$payload options=json.no-string-conversion]
                :if ((($record->"format") != "mikrowarp-operation-v1") || (($record->"owner") != ($c->"owner"))) do={ :error "Journal owner differs" }
                $mikrowarpNativeRecordCheck record=$record
                :if (([:len $mikrowarpNativeState] = 0) || (($record->"sequence") > ($mikrowarpNativeState->"sequence"))) do={ :set mikrowarpNativeState $record }
            } on-error={ :set invalid ($invalid + 1) }
        }
    }
    :if (([:len $mikrowarpNativeState] = 0) && ($invalid > 0)) do={ :error "No valid operation journal; existing state was preserved" }
    :if ([:len $mikrowarpNativeState] = 0) do={ :set mikrowarpNativeState {"format"="mikrowarp-operation-v1";"owner"=($c->"owner");"sequence"=0;"phase"="empty";"current"=[:toarray ""];"previous"=[:toarray ""]} }
    :if ($action = "status") do={
        $mikrowarpNativeLog text=("Gateway " . ($c->"gateway") . "; operation " . ($mikrowarpNativeState->"phase"))
        :if ([$mikrowarpNativeLive itemName="mikrowarp"]) do={ :local status [$mikrowarpNativeShell itemName="mikrowarp" command="/usr/local/sbin/mikrowarp"]; $mikrowarpNativeLog text=($status->"output") } else={ $mikrowarpNativeLog text="Container is not running." }
        :return true
    }
    :local phase ($mikrowarpNativeState->"phase")
    :local pending (($phase != "empty") && ($phase != "complete") && ($phase != "aborted"))
    :if ($action = "abort") do={ :if ($pending) do={ $mikrowarpNativeAbort } else={ $mikrowarpNativeLog text="No pending operation." }; :return true }
    :if ($pending && ($action = "rollback")) do={ :error "An operation is pending; re-import to resume or select abort first" }
    :if (!$pending) do={
        :local current ($mikrowarpNativeState->"current")
        :local target $mikrowarpNativeRelease
        :local kind "update"; :local restore ""
        :if ($action = "rollback") do={
            :local previous ($mikrowarpNativeState->"previous")
            :if ([:len ($previous->"snapshot")] = 0) do={ :error "No previous accepted image and state are available" }
            :set target ($previous->"bundle"); :set restore ($previous->"snapshot"); :set kind "rollback"
        }
        :if ([:len ($current->"image_id")] = 0) do={ :set kind "install" } else={
            :local id [$mikrowarpNativeContainer itemName="mikrowarp" bundle=$current]
            :if (($id = "") || ([/container/get $id image-id] != ($current->"image_id"))) do={ :error "Current container differs from the saved installation" }
            :if (($target->"image_id") = ($current->"image_id")) do={
                $mikrowarpNativeLog text=("Already installed. Gateway " . ($c->"gateway") . ". No restart or routing changes.")
                :if ([$mikrowarpNativeLive itemName="mikrowarp"]) do={ :local status [$mikrowarpNativeShell itemName="mikrowarp" command="/usr/local/sbin/mikrowarp"]; $mikrowarpNativeLog text=($status->"output") }
                :return true
            }
            :if ([:len [/file/find where name=($base . "/archives/" . ($current->"sha256") . ".tar.gz")]] = 0) do={ :error "Current image archive is missing; update cannot preserve rollback" }
        }
        :if (([:len [/container/find where name="mikrowarp-next"]] > 0) || ([:len [/container/find where name="mikrowarp-old"]] > 0)) do={ :error "A staging container name is already occupied" }
        :set ($mikrowarpNativeState->"kind") $kind
        :set ($mikrowarpNativeState->"old") $current
        :set ($mikrowarpNativeState->"new") $target
        :set ($mikrowarpNativeState->"formerPrevious") ($mikrowarpNativeState->"previous")
        :set ($mikrowarpNativeState->"snapshot") [:rndstr from="0123456789abcdef" length=64]
        :set ($mikrowarpNativeState->"restore") $restore
        :set ($mikrowarpNativeState->"snapshotCreated") false
        $mikrowarpNativeSave phase="staging"
    }
    :if (![$mikrowarpNativeAvailable network=($c->"network")]) do={ :error "The saved transit subnet now conflicts with another address or route" }
    $mikrowarpNativeMkdir path=($base . "/data")
    $mikrowarpNativeWrite path=($base . "/data/owner.txt") text=($c->"owner")
    :foreach directory in={"state";"logs";"diagnostics"} do={ $mikrowarpNativeMkdir path=($base . "/data/" . $directory) }
    $mikrowarpNativeNetwork
    $mikrowarpNativeLog text=("Using " . $base . "; uplink " . ($c->"uplink") . "; gateway " . ($c->"gateway"))
    $mikrowarpNativeResume
    $mikrowarpNativeLog text=("Ready. Gateway " . ($c->"gateway") . ". Traffic selection remains yours.")
}


:onerror err in={
    # Parent records this background job before it can change router state.
    :local registered false
    :for i from=1 to=20 do={
        :if (!$registered) do={
            :local lock [:deserialize from=json value=[/file/get [find where name="mikrowarp-operation.lock.json"] contents] options=json.no-string-conversion]
            :if (($lock->"token") != ($input->"token")) do={ :error "Operation lock changed" }
            :set registered (($lock->"job") != "")
            :if (!$registered) do={ :delay 500ms }
        }
    }
    :if (!$registered) do={ :error "Importer disconnected before starting; re-import" }
    # Reboots can leave an operation log after its lock disappeared. Clean only
    # this reserved filename shape with our marker (or an interrupted empty file).
    :foreach f in=[/file/print as-value where name~"^mikrowarp-operation-[0-9a-f]+[.]txt\$"] do={
        :local filename ($f->"name")
        :if (([:len $filename] = 56) && ($filename != ($input->"log"))) do={
            :local content [/file/get ($f->".id") contents]
            :if (([:len $content] = 0) || ([:pick $content 0 [:len "# MikroWARP\n"]] = "# MikroWARP\n")) do={ /file/remove ($f->".id") }
        }
    }
    $mikrowarpNativeLog text="MikroWARP Standard: RouterOS installation and management"
    $mikrowarpNativeMain action=$action
    $mikrowarpNativeLog text="RESULT success"
} do={
    :global mikrowarpNativeLog
    $mikrowarpNativeLog text=("Error: " . $err)
    $mikrowarpNativeLog text="RESULT failed; the saved operation can be resumed by re-importing"
}
/system/script/environment/remove [find where name~"^mikrowarpNative"]

}]
:set ($lock->"job") [:tostr $job]
:local stamp [:tostr [/system/script/job/get $job started]]
:set ($lock->"started") $stamp
/file/set [find where name=$lockPath] contents=[:serialize to=json value=$lock options=json.no-string-conversion]
:local shown 0
:while ([$alive job=$job started=$stamp]) do={
    :delay 1s
    :local file [/file/find where name=$logPath]
    :if ([:len $file] > 0) do={
        :local output [/file/get $file contents]
        :if ([:len $output] < $shown) do={ :set shown 0 }
        :if ([:len $output] > $shown) do={ :put [:pick $output $shown [:len $output]]; :set shown [:len $output] }
    }
}
:local output ""
:if ([:len [/file/find where name=$logPath]] > 0) do={ :set output [/file/get [find where name=$logPath] contents] }
:if ([:len $output] > $shown) do={ :put [:pick $output $shown [:len $output]] }
:local current [/file/find where name=$lockPath]
:if ([:len $current] > 0) do={
    :local record [:deserialize from=json value=[/file/get $current contents] options=json.no-string-conversion]
    :if (($record->"token") = $token) do={ /file/remove $current }
}
# Keep one useful operation log, removing only the previously recorded owned log.
:local last [/file/find where name="mikrowarp-last-operation.txt"]
:if ([:len $last] > 0) do={
    :if ([:pick [/file/get $last contents] 0 [:len "# MikroWARP\n"]] = "# MikroWARP\n") do={ /file/remove $last }
}
:if ([:len [/file/find where name="mikrowarp-last-operation.txt"]] = 0) do={
    :if ([:len [/file/find where name=$logPath]] > 0) do={ /file/set [find where name=$logPath] name="mikrowarp-last-operation.txt"; :set logPath "mikrowarp-last-operation.txt" }
} else={
    # An unrelated file owns the preferred log name; retain no temporary log.
    /file/remove [find where name=$logPath]
    :set logPath "terminal output above"
}
:if ([:typeof [:find $output "RESULT success"]] = "nil") do={ :error ("MikroWARP did not finish. Details: " . $logPath . ". Re-import to resume, or select abort.") }
